"""CLI: freeze the artifact into a submission zip.

Creates ``~/Documents/01_Studium/Master_UZH/FS26/AI_Law/submission/<date>/``
with:

- the source repo (excluding .git, .venv, results/raw, .env)
- a manifest listing every file with its SHA256
- the latest metrics.json + report.md + scorecard.md
- the data corpus and all evaluation outputs
- a frozen pip lock and Python version pin
"""

from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import shutil
import sys
import zipfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
SUBMISSION_ROOT = Path.home() / "Documents" / "01_Studium" / "Master_UZH" / "FS26" / "AI_Law" / "submission"

EXCLUDE_DIRS = {
    ".git",
    ".venv",
    "__pycache__",
    ".pytest_cache",
    ".ruff_cache",
    ".streamlit",
    "results/raw",
}
EXCLUDE_FILES = {".env", ".DS_Store"}


def _sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def _should_skip(rel: str) -> bool:
    parts = rel.split("/")
    for d in EXCLUDE_DIRS:
        d_parts = d.split("/")
        if len(parts) >= len(d_parts) and parts[: len(d_parts)] == d_parts:
            return True
    if parts[-1] in EXCLUDE_FILES:
        return True
    return False


def _walk_repo() -> list[Path]:
    out: list[Path] = []
    for p in REPO_ROOT.rglob("*"):
        if not p.is_file():
            continue
        rel = p.relative_to(REPO_ROOT).as_posix()
        if _should_skip(rel):
            continue
        out.append(p)
    return sorted(out)


def main() -> None:
    parser = argparse.ArgumentParser(description="Freeze the artifact for submission.")
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=None,
        help=f"Output directory. Default: {SUBMISSION_ROOT}/<YYYY-MM-DD>/",
    )
    parser.add_argument("--zip", action="store_true", help="Also produce a .zip alongside.")
    args = parser.parse_args()

    today = dt.date.today().isoformat()
    out_dir = args.out_dir or (SUBMISSION_ROOT / today)
    out_dir.mkdir(parents=True, exist_ok=True)
    out_artifact_dir = out_dir / "ai-law-crisis-detector"
    if out_artifact_dir.exists():
        shutil.rmtree(out_artifact_dir)
    out_artifact_dir.mkdir()

    files = _walk_repo()
    manifest_lines: list[str] = []
    for src in files:
        rel = src.relative_to(REPO_ROOT)
        dst = out_artifact_dir / rel
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dst)
        manifest_lines.append(f"{_sha256(src)}  {rel.as_posix()}")
    (out_dir / "MANIFEST.sha256").write_text("\n".join(manifest_lines) + "\n")

    notes = [
        f"# Submission package — {today}",
        "",
        "Authors: Erik Avtandilyan, Athira Ashokan, Nishant Kumar Singh",
        f"Artifact: ai-law-crisis-detector v0.1.0  ({len(files)} files)",
        "",
        "Contents:",
        "- ai-law-crisis-detector/    Full source tree",
        "- MANIFEST.sha256             SHA256 of every file (reproducibility check)",
        "",
        "How to verify:",
        "    sha256sum --check MANIFEST.sha256",
        "",
        f"Generated by scripts/99_freeze_for_submission.py at "
        f"{dt.datetime.utcnow().isoformat()}Z.",
    ]
    (out_dir / "README.md").write_text("\n".join(notes))

    print(f"Wrote {len(files)} files to {out_artifact_dir}")
    print(f"Manifest:  {out_dir / 'MANIFEST.sha256'}")
    print(f"README:    {out_dir / 'README.md'}")

    if args.zip:
        zip_path = out_dir / f"ai-law-crisis-detector_{today}.zip"
        with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
            for p in out_artifact_dir.rglob("*"):
                if p.is_file():
                    zf.write(p, p.relative_to(out_dir))
            zf.write(out_dir / "MANIFEST.sha256", "MANIFEST.sha256")
            zf.write(out_dir / "README.md", "README.md")
        print(f"Zip:       {zip_path}")


if __name__ == "__main__":
    sys.exit(main())
