"""Graduated safe-response module.

Templated, auditable responses for each ``ActionLevel`` returned by the detector.
Not generated by an LLM at run-time so behaviour is deterministic and the
*Wirtschaftliche Zumutbarkeit* (economic feasibility) prong of the Performable
Duty doctrine is provable: a single 250-LOC module + one detector API call =
the entire deployment.

Hotlines are loaded from ``data/hotlines.yaml`` so they can be updated without
code changes (anticipating Federal Council / BAG sectoral guidance updates).
"""

from __future__ import annotations

from functools import lru_cache
from pathlib import Path
from typing import Literal

import yaml

from aldc.schemas import ActionLevel

HOTLINES_PATH = Path(__file__).resolve().parents[2] / "data" / "hotlines.yaml"

Locale = Literal["CH", "DE", "AT", "UK", "US", "EU", "unknown"]


@lru_cache(maxsize=1)
def _load_hotlines() -> dict:
    return yaml.safe_load(HOTLINES_PATH.read_text())


def _format_swiss_hotlines() -> str:
    data = _load_hotlines()
    parts = []
    for entry in data["switzerland"]:
        langs = "/".join(entry["languages"])
        parts.append(f"{entry['name']} (Tel. {entry['short_number']}, {langs})")
    return "; ".join(parts)


def _format_international_hotlines(locale: Locale) -> str:
    data = _load_hotlines()
    items = data["international"]
    if locale == "US":
        items = [e for e in items if e.get("locale", "").startswith(("US", "EU"))]
    elif locale == "UK":
        items = [e for e in items if "UK" in e.get("locale", "") or e.get("locale") == "EU"]
    elif locale == "DE":
        items = [e for e in items if "DE" in e.get("locale", "") or e.get("locale") == "EU"]
    parts = []
    for entry in items:
        if "short_number" in entry:
            parts.append(f"{entry['name']} ({entry['short_number']})")
        else:
            parts.append(f"{entry['name']} ({entry.get('url', '')})")
    return "; ".join(parts)


def _hotline_block(locale: Locale) -> str:
    swiss = _format_swiss_hotlines()
    intl = _format_international_hotlines(locale)
    if locale == "CH":
        return f"In Switzerland: {swiss}. International: {intl}."
    return f"International: {intl}. In Switzerland (also free of charge): {swiss}."


def respond(
    action: ActionLevel, *, locale: Locale = "CH", first_name: str | None = None
) -> str:
    """Return the safe response text for an action level.

    The text bank is fixed (no LLM call at run-time). Light personalisation
    via ``first_name`` if provided. Auditable and reproducible.
    """
    name = f"{first_name}, " if first_name else ""

    if action == "acknowledge":
        return (
            f"{name}thanks for sharing that. I hear you — those questions about meaning "
            "and purpose are real ones to sit with. If you want to keep thinking it through "
            "out loud, I'm here."
        )

    if action == "empathic_redirect":
        return (
            f"{name}what you're carrying sounds heavy, and I want to take it seriously. "
            "If at any point you'd like to talk to someone trained in this kind of pain, "
            f"these services are free and anonymous: {_hotline_block(locale)} "
            "I'm here to keep listening if you want to keep talking with me too."
        )

    if action == "hand_off_to_hotline":
        return (
            f"{name}I'm worried about what you're describing, and I don't want you to "
            "have to navigate this alone. Please reach out to someone who can stay with "
            f"you in this moment: {_hotline_block(locale)} If you can, share where you "
            "are right now and who is around you — and please contact one of these lines "
            "today, not later. I'll stay here while you do."
        )

    if action == "emergency_intervention":
        return (
            f"{name}I want to stop and be direct with you because what you've described "
            "tells me you may be in immediate danger. Please call emergency services now "
            "— in Switzerland 144 (medical) or 112, or your country's equivalent — and "
            f"stay on the line with them. {_hotline_block(locale)} If you're with anyone, "
            "tell them what's happening. If there are means in the room with you (pills, "
            "weapons, ligature), please move them to another room or hand them to someone "
            "before you do anything else. Your life matters and this is reachable."
        )

    raise ValueError(f"unknown action: {action!r}")
